name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # or any branch you want to trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create zip file
      run: zip -r code.zip . -x "*.git*"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      run: echo "dckr_pat_VcrRCzS3nqBOaID4hyOm0qziuAk" | docker login -u rakrocks18 --password-stdin

    

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: rakshit18/amayori-lang:latest
        build-args: |
          ZIP_FILE=code.zip