name: CI/CD Pipeline

on:
  schedule:
    # Runs at 06:45 UTC every day
    - cron: '45 6 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

env:
  DOCKER_REPOSITORY: your-docker-username/amayori-lang

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang llvm

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Determine version and tag
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "schedule" ]]; then
          echo "::set-output name=version::nightly-$(date +'%Y%m%d')"
          echo "::set-output name=release_name::Nightly Build $(date +'%Y-%m-%d')"
          echo "::set-output name=prerelease::true"
        else
          VERSION=$(git describe --tags --always --dirty)
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=release_name::Release $VERSION"
          echo "::set-output name=prerelease::false"
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_REPOSITORY }}:${{ steps.version.outputs.version }}
          ${{ env.DOCKER_REPOSITORY }}:latest

    - name: Create Git Tag
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag -a ${{ steps.version.outputs.version }} -m "${{ steps.version.outputs.release_name }}"
        git push origin ${{ steps.version.outputs.version }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: ${{ steps.version.outputs.release_name }}
        draft: false
        prerelease: ${{ steps.version.outputs.prerelease }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/build/your-binary-name  # Replace with the path to your built binary
        asset_name: amayori-lang-${{ steps.version.outputs.version }}
        asset_content_type: application/octet-stream